"""FastAPI application, shared imports, localization, and process-wide configuration."""

# ==========================================
# 🚀 SAVIA FastAPI Backend
# ==========================================
"""
FastAPI backend for the SAVIA Next.js frontend.
Replaces Flask api_server.py with modern async endpoints.
"""
import math
import os
import base64
import tempfile
import unicodedata
import jwt
import bcrypt
import logging
import auth
import pandas as pd
from datetime import datetime, timedelta
from typing import Optional, Any

from fpdf import FPDF
from fpdf.enums import XPos, YPos
from fastapi import FastAPI, Depends, HTTPException, Query, Header, status, UploadFile, File, Body, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from fastapi.responses import JSONResponse
from pydantic import BaseModel

from repositories.technician_names import DatabaseTechnicianNameRepository
from services.knowledge_import import detect_and_fix_encoding, parse_text_to_rows as _parse_text_to_rows
from services.localization import LocalizationService
from services.technician_identity import TechnicianIdentityService

from db_engine import (
    init_db, get_db, read_sql, _trigger_backup,
    lire_equipements, ajouter_equipement, modifier_equipement, supprimer_equipement,
    lire_interventions, ajouter_intervention, update_intervention_statut, cloturer_intervention,
    lire_pieces, ajouter_piece, modifier_piece, supprimer_piece,
    lire_notifications_pieces, compter_notifications_non_lues, ajouter_notification_piece,
    marquer_notification_lue, marquer_notification_traitee, notifications_rupture_pour_piece,
    ajouter_piece_demandee, lire_pieces_demandees_en_attente, resoudre_piece_demandee, lire_toutes_pieces_demandees,
    lire_contrats, ajouter_contrat, modifier_contrat, supprimer_contrat, generer_planning_from_contrat, get_contract_equipements,
    lire_conformite, ajouter_conformite, supprimer_conformite,
    lire_planning, ajouter_planning, update_planning_statut, supprimer_planning,
    lire_techniciens, ajouter_technicien, update_technicien, supprimer_technicien,
    lire_base,
    lire_audit, log_audit,
    get_config, set_config,
    lire_demandes_intervention,
    lire_clients as db_lire_clients, ajouter_client, modifier_client, supprimer_client,
    migrer_clients_depuis_equipements,
    lire_fabricants, ajouter_fabricant,
    lire_types_equipement_custom, ajouter_type_equipement_custom,
    lire_types_intervention_custom, ajouter_type_intervention_custom,
    lire_notification_schedules, sauvegarder_notification_schedules_batch,
    predict_commande_date, predict_pieces_a_commander,
    update_piece_parameters_batch, calculate_piece_parameters,
)

logger = logging.getLogger("savia-api")

_EN_TRANSLATIONS = {
    "Rapport SAVIA": "SAVIA Report",
    "rapport": "report",
    "Systeme Intelligent de Controle et de Gestion": "Intelligent Control and Management System",
    "Système Intelligent de Contrôle et de Gestion": "Intelligent Control and Management System",
    "Repartition par type": "Breakdown by type",
    "Répartition par type": "Breakdown by type",
    "Type": "Type",
    "Nombre": "Count",
    "RESUME EXECUTIF": "EXECUTIVE SUMMARY",
    "RÉSUMÉ EXÉCUTIF": "EXECUTIVE SUMMARY",
    "POINTS FORTS": "STRENGTHS",
    "POINTS FAIBLES": "WEAKNESSES",
    "RECOMMANDATIONS": "RECOMMENDATIONS",
    "ALERTES CRITIQUES": "CRITICAL ALERTS",
    "TENDANCES": "TRENDS",
    "EVALUATION DE L'EQUIPE": "TEAM EVALUATION",
    "ANALYSE DES COUTS": "COST ANALYSIS",
    "PRIORITES IMMEDIATES": "IMMEDIATE PRIORITIES",
    "CONCLUSION": "CONCLUSION",
    "Excellent": "Excellent",
    "Satisfaisant": "Satisfactory",
    "A ameliorer": "Needs improvement",
    "A améliorer": "Needs improvement",
    "Score global de performance": "Overall performance score",
    "Genere par": "Generated by",
    "Généré par": "Generated by",
    "Genere le": "Generated on",
    "Généré le": "Generated on",
    "Confidentiel": "Confidential",
    "Date": "Date",
    "Client": "Client",
    "Equipement": "Equipment",
    "Équipement": "Equipment",
    "Machine": "Machine",
    "Technicien": "Technician",
    "Techniciens": "Technicians",
    "Tous les techniciens": "All technicians",
    "Statut": "Status",
    "Notes": "Notes",
    "Description": "Description",
    "Solution": "Solution",
    "Solution Appliquee": "Applied solution",
    "Solution Appliquée": "Applied solution",
    "Heure Debut": "Start time",
    "Heure Début": "Start time",
    "Heure Fin": "End time",
    "Trajet (h)": "Travel (h)",
    "Travaux Effectues": "Work Performed",
    "Travaux Effectués": "Work Performed",
    "Travaux Effectues (Multi-Technicien)": "Work Performed (Multi-Technician)",
    "Travaux Effectués (Multi-Technicien)": "Work Performed (Multi-Technician)",
    "References - Pieces Utilisees": "References - Parts Used",
    "Références - Pièces Utilisées": "References - Parts Used",
    "Reference": "Reference",
    "Qte": "Qty",
    "Designation": "Description",
    "Observations": "Comments",
    "Signatures & Approbations": "Signatures & Approvals",
    "Visa Intervenant": "Technician Approval",
    "Visa Client": "Client Approval",
    "Visa Administration": "Administration Approval",
    "Garantie": "Warranty",
    "Contrat": "Contract",
    "OUI": "YES",
    "NON": "NO",
    "N° Serie": "Serial No.",
    "N° de série": "Serial No.",
    "Marque/Modele": "Brand/Model",
    "Marque / Modèle": "Brand / Model",
    "Localisation": "Location",
    "Région / Ville": "Region / City",
    "Adresse": "Address",
    "Téléphone": "Phone",
    "INFORMATIONS ÉQUIPEMENT": "EQUIPMENT INFORMATION",
    "Attestation de Bon Fonctionnement": "Certificate of Proper Operation",
    "Pour le client": "For the client",
    "Pour": "For",
    "Ce document est généré automatiquement par": "This document is automatically generated by",
    "ARTICLE": "ARTICLE",
    "LE PRESTATAIRE": "THE SERVICE PROVIDER",
    "LE CLIENT": "THE CLIENT",
    "PLANNING MAINTENANCE": "MAINTENANCE PLANNING",
    "Filtre": "Filter",
    "Tous les clients": "All clients",
    "Nombre d'interventions": "Number of interventions",
    "RAPPORT COMPARATEUR PLANNING": "PLANNING COMPARISON REPORT",
    "INFORMATIONS ÉQUIPEMENT": "EQUIPMENT INFORMATION",
    "PLANNING RÉEL (Nouvelle date)": "ACTUAL PLANNING (New date)",
    "PLANNING DÉCALÉ (Date originale)": "SHIFTED PLANNING (Original date)",
    "CHANGEMENTS": "CHANGES",
    "RAISONS DU DÉCALAGE": "REASONS FOR RESCHEDULING",
    "Date modifiée": "Date changed",
    "Technicien modifié": "Technician changed",
    "Non assigné": "Unassigned",
    "Rapport généré automatiquement par SAVIA": "Report automatically generated by SAVIA",
    "Page": "Page",
    "Cloturee": "Closed",
    "Clôturée": "Closed",
    "En cours": "In progress",
    "En attente de piece": "Waiting for part",
    "En attente de pièce": "Waiting for part",
    "Planifiée": "Scheduled",
    "Réalisée": "Completed",
    "En retard": "Overdue",
    "Décalé": "Rescheduled",
    "Corrective": "Corrective",
    "Préventive": "Preventive",
    "Installation": "Installation",
    "Formation": "Training",
    "Démonstration": "Demo",
    "Coût": "Cost",
    "Coût total": "Total cost",
    "Pièces": "Parts",
    "Main d'oeuvre": "Labor",
    "Main d'œuvre": "Labor",
    "Durée": "Duration",
    "Durée totale": "Total duration",
    "Déplacement": "Travel",
    "Déplacement total": "Total travel",
    "Revenu": "Revenue",
    "Couts": "Costs",
    "Coûts": "Costs",
    "Rentables": "Profitable",
    "Clients Couteux": "High-cost Clients",
    "Clients Coûteux": "High-cost Clients",
    "Causes Identifiees": "Identified Causes",
    "Causes Identifiées": "Identified Causes",
    "Optimisations Proposees": "Proposed Optimizations",
    "Optimisations Proposées": "Proposed Optimizations",
    "Analyse TCO - Cout Total de Possession": "TCO Analysis - Total Cost of Ownership",
    "Analyse TCO - Coût Total de Possession": "TCO Analysis - Total Cost of Ownership",
    "Analyse TCO — Cout Total de Possession": "TCO Analysis - Total Cost of Ownership",
    "Analyse TCO — Coût Total de Possession": "TCO Analysis - Total Cost of Ownership",
    "Analyse TCO — Total Cost de Possession": "TCO Analysis - Total Cost of Ownership",
    "Total Cost de Possession": "Total Cost of Ownership",
    "Cost de Possession": "Cost of Ownership",
    "Clients Performants": "High-Performing Clients",
    "Recommendations Strategiques": "Strategic Recommendations",
    "Recommendations Stratégiques": "Strategic Recommendations",
    "Recommandations Strategiques": "Strategic Recommendations",
    "Recommandations Stratégiques": "Strategic Recommendations",
    "Couteux": "High-cost",
    "Coûteux": "High-cost",
    "Identifiees": "Identified",
    "Identifiées": "Identified",
    "Proposees": "Proposed",
    "Proposées": "Proposed",
    "Strategiques": "Strategic",
    "Stratégiques": "Strategic",
    "Analyse From Risk": "Risk Analysis",
    "Risk de": "Risk of",
    "Action immédiate": "Immediate action",
    "Curatif historique": "Historical corrective",
    "Préventif proposé": "Proposed preventive",
    "Cibles": "Targets",
    "Recommendations d'Achat": "Purchasing Recommendations",
    "Plan d'Achat Planifie": "Planned Purchasing Plan",
    "Plan d'Achat Planifié": "Planned Purchasing Plan",
    "Impact Budget": "Budget Impact",
    "Coût total commande": "Total order cost",
    "Total cost commande": "Total order cost",
    "Résultat de l'AAInalysis": "Analysis Result",
    "Résultat de l'Analyse": "Analysis Result",
    "AAInalysis": "AI analysis",
    "Main d'oeuvre": "Labor",
    "Main d'œuvre": "Labor",
    "préventif": "preventive",
    "Préventif": "Preventive",
    "pièces": "parts",
    "Pièces": "Parts",
    "coûts": "costs",
    "Coûts": "Costs",
    "ANALYSE FINANCIERE IA": "AI FINANCIAL ANALYSIS",
    "ANALYSE FINANCIÈRE IA": "AI FINANCIAL ANALYSIS",
    "Date installation": "Installation date",
    "Sous garantie": "Under warranty",
    "Sous contrat": "Under contract",
    "Oui": "Yes",
    "Non": "No",
    "Nom et signature": "Name and signature",
    "Nom, signature et cachet": "Name, signature and stamp",
    "Cet équipement est sous garantie jusqu'au": "This equipment is under warranty until",
    "Nous attestons que l'équipement susmentionné a été vérifié et testé par nos techniciens qualifiés.": "We certify that the above-mentioned equipment has been checked and tested by our qualified technicians.",
    "Tous les paramètres de fonctionnement sont conformes aux spécifications du fabricant.": "All operating parameters comply with the manufacturer's specifications.",
    "L'équipement est apte à une utilisation normale dans le cadre de ses fonctions désignées.": "The equipment is fit for normal use within its intended functions.",
    "La société": "The company",
    "atteste par la présente que l'équipement ci-dessous": "hereby certifies that the equipment below",
    "installé chez le client": "installed at client",
    "est en parfait état de fonctionnement": "is in perfect working order",
    "à la date du": "as of",
    "CONTRAT DE MAINTENANCE": "MAINTENANCE CONTRACT",
    "Réf.": "Ref.",
    "Établi le": "Issued on",
    "Ci-après dénommé": "Hereinafter referred to as",
    "le Client": "the Client",
    "Objet du contrat": "Contract purpose",
    "Equipements couverts": "Covered equipment",
    "Équipements couverts": "Covered equipment",
    "Durée du contrat": "Contract duration",
    "Prestations incluses": "Included services",
    "Obligations du prestataire": "Service provider obligations",
    "Obligations du client": "Client obligations",
    "Conditions financières": "Financial terms",
    "Conditions financieres": "Financial terms",
    "Confidentialité": "Confidentiality",
    "Confidentialite": "Confidentiality",
    "Résiliation": "Termination",
    "Resiliation": "Termination",
    "Signatures": "Signatures",
    "Notes complémentaires": "Additional notes",
    "Fait à": "Signed in",
    "en deux exemplaires originaux": "in two original copies",
    "Pour le Prestataire": "For the Service Provider",
    "Pour le Client": "For the Client",
    "Montant": "Amount",
    "Date début": "Start date",
    "Date fin": "End date",
    "Date première maintenance": "First maintenance date",
    "Récurrence maintenance": "Maintenance recurrence",
    "Temps de réponse SLA": "SLA response time",
    "Matricule fiscale": "Tax ID",
    "Contact": "Contact",
    "PLANNING RÉEL": "ACTUAL PLANNING",
    "PLANNING DÉCALÉ": "SHIFTED PLANNING",
    "Nouvelle date": "New date",
    "Date originale": "Original date",
    "Raisons du décalage": "Reasons for rescheduling",
    "Changement": "Change",
    "Ancienne valeur": "Old value",
    "Nouvelle valeur": "New value",
    "Maintenance": "Maintenance",
    "Date planifiée": "Scheduled date",
    "Date planifiee": "Scheduled date",
    "Type maintenance": "Maintenance type",
    "Tous": "All",
    "Aucune": "None",
    "Non disponible": "Not available",
    "Journal d'Audit SAVIA": "SAVIA Audit Log",
    "Filtres appliqués": "Applied filters",
    "Filtres appliques": "Applied filters",
    "Utilisateur": "User",
    "Détails": "Details",
    "Details": "Details",
    "Date/Heure": "Date/Time",
    "Période": "Period",
    "Periode": "Period",
    "Par": "By",
    "INFORMATIONS CLIENT": "CLIENT INFORMATION",
    "Rapport PDF des Interventions": "Intervention PDF Report",
    "Générer PDF": "Generate PDF",
    "Génération": "Generation",
    "Date clôture": "Closure date",
    "Date cloture": "Closure date",
    "Aucun log à exporter": "No log to export",
    "Non spécifié": "Not specified",
    "Non specifie": "Not specified",
}


_localization_service = LocalizationService(_EN_TRANSLATIONS, get_config, logger)
_LANG_CONTEXT = _localization_service.language_context
_normalize_lang = _localization_service.normalize_language
_get_app_language = _localization_service.get_app_language
_ai_language_instruction = _localization_service.ai_language_instruction
_translate_text_for_lang = _localization_service.translate_text
_fallback_translate_payload_for_lang = _localization_service.fallback_translate_payload
_force_ai_payload_language = _localization_service.force_ai_payload_language

# ── Helper function to get technician full name from username ─────────
_technician_identity_service = TechnicianIdentityService(
    DatabaseTechnicianNameRepository(get_db),
    logger,
)


_get_technician_fullname = _technician_identity_service.resolve_full_name
_tech_name_or_username_matches = _technician_identity_service.name_or_username_matches


# ── Auto-copy DejaVu Sans from matplotlib on startup ─────────────────
def _ensure_dejavu_font():
    import shutil
    dst = "/app/DejaVuSans.ttf"
    if os.path.exists(dst): return
    try:
        import matplotlib
        src = os.path.join(os.path.dirname(matplotlib.__file__),
                           "mpl-data", "fonts", "ttf", "DejaVuSans.ttf")
        if os.path.exists(src):
            shutil.copy2(src, dst)
            logger.info(f"DejaVu Sans copied: {os.path.getsize(dst):,} bytes")
        else:
            logger.warning("DejaVu not found in matplotlib")
    except Exception as _e:
        logger.warning(f"DejaVu copy failed: {_e}")

_ensure_dejavu_font()

# ── Auto-convert Font Awesome WOFF2 → TTF on startup ─────────────────
def _ensure_fa_font():
    import shutil, subprocess as _sp
    dst = "/app/fa-solid-900.ttf"
    if os.path.exists(dst): return
    src_woff2 = "/usr/local/lib/node_modules/@fortawesome/fontawesome-free/webfonts/fa-solid-900.woff2"
    if not os.path.exists(src_woff2):
        logger.warning("FA woff2 not found - run: npm install @fortawesome/fontawesome-free")
        return
    try:
        from fontTools.ttLib import TTFont
        t = TTFont(src_woff2)
        t.flavor = None
        t.save(dst)
        logger.info(f"Font Awesome TTF ready: {os.path.getsize(dst):,} bytes")
    except Exception as _e:
        logger.warning(f"FA font conversion failed: {_e}")

_ensure_fa_font()
# ─────────────────────────────────────────────────────────────────────
logging.basicConfig(level=logging.INFO)


def _cors_origins():
    """Return configured origins plus the local frontend addresses used in development."""
    configured = [
        origin.strip().rstrip("/")
        for origin in os.getenv("CORS_ORIGINS", "").split(",")
        if origin.strip()
    ]
    local_origins = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:3001",
        "http://127.0.0.1:3001",
    ]
    return list(dict.fromkeys(configured + local_origins))

# ---- Config ----
JWT_SECRET = os.getenv("JWT_SECRET", "sic-terrain-secret-2026")
JWT_EXPIRY_HOURS = 72
security = HTTPBearer(auto_error=False)

IS_PRODUCTION = os.getenv("NODE_ENV") == "production"

# ---- App ----
app = FastAPI(
    title="SAVIA API",
    description="Backend API for SAVIA — Superviseur Intelligent Clinique",
    version="2.0.0",
    docs_url=None if IS_PRODUCTION else "/docs",
    redoc_url=None if IS_PRODUCTION else "/redoc",
    openapi_url=None if IS_PRODUCTION else "/openapi.json"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=_cors_origins(),
    allow_origin_regex=r"^https?://(localhost|127\.0\.0\.1)(:\d+)?$",
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.middleware("http")
async def savia_language_context(request: Request, call_next):
    token = _LANG_CONTEXT.set(_get_app_language(request.headers.get("x-savia-lang")))
    try:
        return await call_next(request)
    finally:
        _LANG_CONTEXT.reset(token)


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    """Return a CORS-compatible JSON error instead of an opaque browser failure."""
    logger.exception("Unhandled API error on %s %s", request.method, request.url.path)
    return JSONResponse(
        status_code=500,
        content={"error": "Erreur interne du serveur"},
    )

__all__ = [name for name in globals() if not name.startswith("__")]
