[server]
runOnSave = true
fileWatcherType = "auto"
enableWebsocketCompression = false
maxMessageSize = 200
enableStaticServing = false

[runner]
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "auto"

[theme]
base = "dark"
primaryColor = "#2dd4bf"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f8fafc"
font = "sans serif"
